# .cpanel.yml
deployment:
  version: 1
  app: mywebsite
  web:
    document_root: /public_html
    files:
      - static/
      - aboutUs.html
      - blog.html
      - index.html
      - mailBody.html
